export { validateOptionalString } from './validateOptionalString'
export { validateRequiredString } from './validateRequiredString'
export { validateOptionalLocation } from './validateOptionalLocation'
export { validateRequiredLocation } from './validateRequiredLocation'
export { validateOptionalNumber } from './validateOptionalNumber'
export { validateMongoObjectId } from './validateMongoObjectId'
export { validateOptionalBoolean } from './validateOptionalBoolean'
export { validateOptionalBedsArray } from './validateOptionalBedsArray'
