interface IHttpStatusCode {
  OK: number
  BAD_REQUEST: number
  UNAUTHORIZED: number
  FORBIDDEN: number
  NOT_FOUND: number
  METHOD_NOT_ALLOWED: number
  INTERNAL_SERVER_ERROR: number
  NOT_IMPLEMENTED: number
  BAD_GATEWAY: number
  SERVICE_UNAVAILABLE: number
}

interface IHttpStatus {
  OK: 'OK'
  BAD_REQUEST: 'BAD_REQUEST'
  UNAUTHORIZED: 'UNAUTHORIZED'
  FORBIDDEN: 'FORBIDDEN'
  NOT_FOUND: 'NOT_FOUND'
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED'
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED'
  BAD_GATEWAY: 'BAD_GATEWAY'
  SERVICE_UNAVAILABLE:'SERVICE_UNAVAILABLE'
}

export { IHttpStatusCode, IHttpStatus }
