export { postProfilePayloadValidator, patchProfilePayloadValidator } from './Profile'
export { postHotelPayloadValidator, patchHotelPayloadValidator } from './Hotel'
export { patchRoomTypePayloadValidator, postRoomTypePayloadValidator } from './RoomType'
export { patchBookingPayloadValidator, postBookingPayloadValidator } from './Booking'
export { postLoginPayloadValidator } from './Login'
export { postOneTimePasswordPayloadValidator } from './OneTimePassword'
export { postCreateOrderPayloadValidator } from './Order'
export { postJwtPayloadValidator } from './Jwt'
export { patchRateModifierPayloadValidator, postRateModifierPayloadValidator } from './RateModifier'
